# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab9_2_1/Nexys4DDR_Master.xdc

# IP: C:/Users/Firev/OneDrive/Documents/GitHub/Steven-Jugler-ENES-246-501/Steven ENES/11IP/2_Square_Root_IP/SquareRootIP.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet
